---
abstract: unknown
author:
  - 'Hugh Esco <hesco@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::Exception: 0.32
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.74, CPAN::Meta::Converter version 2.132140'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-ConfigSimple
no_index:
  directory:
    - t
    - inc
requires:
  Config::Simple::Extended: 0.15
  Mojolicious: 4.45
version: 0.01
